client/chark/App.js, client/chark/assets/ticket.json, client/chark/src/screens/Invite/TemplateItem/index.jsx, client/chark/src/screens/Invite/index.jsx
Updates:
- Added pull to refresh in the Flat List.
- Design/Functionality changes to Buttons, Flat List and Webview(The webview is hidden by default and will be updated when the selected template is generated).
- Updated WebView according to the template selected.
=> Display webview according to the template selected

client/chark/App.js, client/chark/android/app/src/main/AndroidManifest.xml, client/chark/babel.config.js, client/chark/index.js, client/chark/package-lock.json, client/chark/package.json, client/chark/src/connect.js, client/chark/src/screens/Scanner/index.jsx
Added QR code scanner.
Packages added for the scanner:
- react-native-vision-camera
- vision-camera-code-scanner
- react-native-reanimated
Docs: 
https://github.com/rodgomesc/vision-camera-code-scanner
https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/
After installing the packages, if there's any error related to `react-native-reanimated/plugin` library, please reset the cache when you start the app using: `npm start -- --reset-cache`.
=> Add QR code scanner and build connection with backend

client/chark/App.js, client/chark/package-lock.json, client/chark/package.json, client/chark/src/config/constants.js, client/chark/src/screens/Scanner/index.jsx, client/chark/src/screens/TallyAccept/index.jsx, client/chark/src/screens/TallyRequest/index.jsx
Initial setup for processing tally
=> Add initial processing of tally

client/chark/.detoxrc.js, client/chark/.gitignore, client/chark/README.md, client/chark/android/app/build.gradle, client/chark/android/app/src/androidTest/java/org/mychips/chark/DetoxTest.java, client/chark/android/app/src/main/AndroidManifest.xml, client/chark/android/app/src/main/res/xml/network_security_config.xml, client/chark/android/build.gradle, client/chark/bin/test-e2e, client/chark/e2e/connection.test.js, client/chark/e2e/jest.config.js, client/chark/e2e/utils/connection.js, client/chark/package-lock.json, client/chark/package.json, client/chark/src/servicon.js
- Setup E2E testing with detox.
- Contains the connection test with the backend.
- Add README file for the app
=> Setup detox and add a test case for ticket connection

client/chark/ios/Podfile.lock, client/chark/ios/chark.xcodeproj/project.pbxproj, client/chark/package-lock.json, client/chark/package.json, client/chark/src/utils/file-manager.js
=> Fix build issue

client/chark/ios/chark.xcodeproj/project.pbxproj, client/chark/ios/chark/Info.plist, client/chark/ios/charkTests/Info.plist, client/chark/src/screens/Setting/GenerateKey/ExportModal/index.jsx, client/chark/src/screens/ShareTally/index.jsx, client/chark/src/utils/file-manager.js
- Adds share and download option for iOS.
=> Add share and download option for iOS

client/chark/src/screens/ImportKeyScreen/index.jsx, client/chark/src/screens/Setting/GenerateKey/ExportKey/index.jsx, client/chark/src/screens/Setting/GenerateKey/ExportModal/index.jsx, client/chark/src/screens/Setting/GenerateKey/PostGenerate/index.jsx, client/chark/src/screens/Setting/GenerateKey/index.jsx, client/chark/src/screens/Setting/index.jsx, client/chark/src/screens/Tally/TallyPreview/GenerateKeysDialog/index.jsx, client/chark/src/screens/Tally/TallyPreview/index.jsx, client/chark/src/services/profile.js, client/chark/src/utils/file-manager.js, client/chark/src/utils/keychain-store.js, client/chark/src/utils/message-signature.js
- Create keys automatically on accept tally if user wish to.
- Allow option to use imported private key.
- Allow user to export saved private key.
=> Handle signing key

client/chark/src/hooks/useLanguage.js, client/chark/src/screens/Invite/TemplateItem/index.jsx, client/chark/src/screens/Tally/ChitDetail/index.jsx, client/chark/src/screens/Tally/ChitHistory/index.jsx, client/chark/src/screens/Tally/CommonTallyView/index.jsx, client/chark/src/screens/Tally/PaymentDetail/index.jsx, client/chark/src/screens/Tally/RequestDetail/index.jsx, client/chark/src/screens/Tally/TallyEditView.jsx, client/chark/src/screens/Tally/TallyItem/index.jsx, client/chark/src/services/tally.js
- Display of Entity/agent names.
- Handle direct payment requests.
=> Direct payment refinements

client/chark/src/screens/Home/index.jsx, client/chark/src/screens/Tally/TallyPreview/index.jsx, client/chark/src/servicon.js
=> QA: Server connected position

client/chark/src/screens/Tally/TallyPreview/index.jsx
=> QA: Buttons at bottom of the tally preview page

client/chark/src/screens/Tally/TallyEditView.jsx, client/chark/src/screens/TallyReview/TallyReviewView.jsx
https://github.com/gotchoices/MyCHIPs/assets/143530065/a6837bcb-38ac-48e3-a34d-b0fb80721499
=> MD-126 QA: Cannot edit the holder terms for a draft tally

client/chark/src/screens/Filter/index.jsx, client/chark/src/screens/Invite/index.jsx
Work on following fixes:
1. QA: Reset button functionality on filters page[MD-124]
2. QA: Remove title from filters page and working tallies page[MD-123]
=> QA: Remove title from filter page and invite page & fix reset button functionality

client/chark/src/components/Button/index.jsx, client/chark/src/navigation/Navigator.jsx, client/chark/src/screens/Notification/NotificationItem/index.jsx, client/chark/src/screens/Notification/NotificationScreen/index.jsx, client/chark/src/screens/Tally/Banner/index.jsx, client/chark/src/screens/Tally/Header/index.jsx
Created notification and UI designs.
However the notification are shown using dummy data and needs further discussion.
=> Created notification screen

client/chark/package-lock.json, client/chark/package.json, client/chark/src/components/Button/index.jsx, client/chark/src/screens/Invite/index.jsx, client/chark/src/screens/Notification/NotificationItem/index.jsx, client/chark/src/screens/Notification/NotificationScreen/index.jsx
Created swipeable component to delete draft tallies
=> Created swipeable component to delete draft tallies

client/chark/package-lock.json, client/chark/src/screens/Notification/NotificationComponent/index.jsx, client/chark/src/screens/Recieve/index.jsx
=> Created new notification component

client/chark/src/components/SocketProvider.jsx, client/chark/src/context/SocketContext.js, client/chark/src/redux/openTalliesSlice.js, client/chark/src/screens/Tally/PaymentDetail/index.jsx, client/chark/src/screens/Tally/Success/index.jsx, client/chark/src/screens/Tally/index.jsx
For now, I have fetched the tally that I get from asynchronously after the chit payment and update the list with the net value. 
Let me know if I can use just the asynchronous data to update the list.
=> Handle asynchronous chit transactions

client/chark/src/navigation/Navigator.jsx, client/chark/src/screens/Invite/TallyEntryModal.jsx, client/chark/src/screens/Invite/index.jsx, client/chark/src/screens/Notification/NotificationScreen/index.jsx, client/chark/src/screens/Notification/NotificationTallyRequest/index.jsx
=> Displayed notification list with action tallies

client/chark/src/redux/workingTalliesSlice.js, client/chark/src/screens/Invite/index.jsx
User should be able to delete tallies onswipe
=> User should be able to delete tallies onswipe

client/chark/src/screens/Tally/TallyEditView.jsx, client/chark/src/screens/TallyReview/TallyReviewView.jsx
=> When a user doesn't have a profile photo display CID instead

client/chark/src/screens/Invite/TemplateItem/TallyTrailingIcon.jsx
=> The yellow warning sign should be red

client/chark/src/components/SocketProvider.jsx, client/chark/src/redux/activitySlice.js, client/chark/src/redux/chitSlice.js, client/chark/src/screens/Tally/PendingChits/ChitItem.jsx, client/chark/src/screens/Tally/PendingChits/index.jsx, client/chark/src/screens/Tally/index.jsx
Chits missing state translations:
```
A.void
A.good
```
And I think these data dictionaries should be interchanged:
```  
{H.offer.draft {You Revised}		{You have marked the tally offer for revision}}
{P.draft.draft {Tally Revised}	{The other party has marked the tally offer for revision}}
```
=> Add data dictionary for notification panel

client/chark/src/navigation/Navigator.jsx, client/chark/src/redux/activitySlice.js, client/chark/src/screens/Invite/TallyEntryModal.jsx, client/chark/src/screens/Tally/CertificateInformation.jsx, client/chark/src/screens/Tally/TallyEditView.jsx, client/chark/src/screens/Tally/TallyPreview/index.jsx, client/chark/src/screens/Tally/TallyRequest/Certificates.jsx, client/chark/src/screens/Tally/TallyRequest/CustomCertificate.jsx, client/chark/src/screens/Tally/TallyRequest/RequestStart.jsx, client/chark/src/screens/Tally/TallyRequest/index.jsx
- Sort chits by descending order by creating date on activity screen
- Fix back button issue from the contract screen.
=> Data sort activity for chits
